name: Update list

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # 检查 curl 是否存在，如果不存在则安装 (或者检查任何你认为需要的工具)
          if ! command -v curl &> /dev/null
          then
            sudo apt-get update
            sudo apt-get install -y curl grep awk sort uniq
          fi

      - name: Run update script
        run: |
          set -e  # 遇到错误立即退出
          cd res
          ./update-chnlist.sh
          ./update-chnroute.sh
          ./update-chnroute6.sh
          ./update-gfwlist.sh
        # 捕捉脚本执行的错误
        continue-on-error: false

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add . # 添加所有修改过的文件

          if ! git diff --cached --quiet; then
            git commit -m "Automated list updates"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
